### ISSUE TITLE
How to access all fields of a struct?

### ISSUE THREAD

**Issue by mgholam** [viant/xunsafe#5]
Hi, 
I would like to access all the fields of a struct and check it's value with your code, currently I'm using the following code based on normal `reflect`:
```go
func anyContains[T any](item *T, val string) bool {
	// this reflection is 2x faster any other way
	e := reflect.ValueOf(item).Elem()
	for i := 0; i < e.NumField(); i++ {
		vv := e.Field(i).String()
		// tolower is 5x slower 146ms than not 27ms (power save mode)
		//            5x         39ms          10ms (performance mode)
 	       //if strings.Contains(strings.ToLower(vv), val) {
		if strings.Contains(vv, val) {
			return true
		}
	}
	return false
}
```

**Comment by adranwit** [comment]
Here is snippet below, 


package xx_test

import (
	"github.com/viant/xunsafe"
	"reflect"
	"strings"
	"testing"
	"unsafe"
)

type Foo struct {
	Name        string
	Description string
}

func TestIt(t *testing.T) {
}

func BenchmarkContainsXunsafe(b *testing.B) {
	for i := 0; i < b.N; i++ {
		anyXunsafeContains(&Foo{Name: "X"}, "abcd")
	}
}

func BenchmarkContainsRelfect(b *testing.B) {
	for i := 0; i < b.N; i++ {
		anyReflectContains(&Foo{Name: "abc"}, "abcd")
	}
}

var xStruct *xunsafe.Struct

func anyXunsafeContains[T any](item *T, val string) bool {
	if xStruct == nil {
		xStruct = xunsafe.NewStruct(reflect.TypeOf(item))
	}
	// this reflection is 2x faster any other way
	//e := reflect.ValueOf(item).Elem()
	ptr := unsafe.Pointer(item)
	for i := range xStruct.Fields {
		candidate := xStruct.Fields[i].String(ptr)
		//if strings.Contains(strings.ToLower(vv), val) {
		if strings.Contains(candidate, val) {
			return true
		}
	}
	return false
}

func anyReflectContains[T any](item *T, val string) bool {
	// this reflection is 2x faster any other way
	e := reflect.ValueOf(item).Elem()
	for i := 0; i < e.NumField(); i++ {
		vv := e.Field(i).String()
		// tolower is 5x slower 146ms than not 27ms (power save mode)
		//            5x         39ms          10ms (performance mode)
		//if strings.Contains(strings.ToLower(vv), val) {
		if strings.Contains(vv, val) {
			return true
		}
	}
	return false
}


note that to gain perfomance xunsafe.Struct or xunsafe.Field have to be cached,
